### ISSUE TITLE
Hello, when are you planning to release your code? 

### ISSUE THREAD

**Issue by winnerwu6** [Charles-Xie/CQL#2]

**Comment by Charles-Xie** [comment]
Hi,
we will release the code this month (June).

**Comment by winnerwu6** [comment]
July is coming to an end, are you really going to release the code?

**Comment by Charles-Xie** [comment]
Yes, in a few days.

**Comment by Charles-Xie** [comment]
Very sorry for the delay. I was occupied with some works in school.
The code is just released. Thanks for the attention to our work. :sunflower: :sunflower: :sunflower:
