### ISSUE TITLE
VCOCO Result

### ISSUE THREAD

**Issue by songguoatongmu** [Charles-Xie/CQL#6]
Thanks for your code realease! However, I've observed that when using the QPIC+CQL checkpoint on the VCOCO dataset, I couldn't achieve the results you reported (63.57, 65.70). I obtained results of 60.83 and 62.91. Did I do something wrong?

**Comment by Charles-Xie** [comment]
The evaluation on V-COCO is same as QPIC and many other methods (GEN-VLKT, etc.). This is answered in previous issues of QPIC. Please see this: https://github.com/hitachi-rd-cv/qpic/issues/18 and this https://github.com/hitachi-rd-cv/qpic/issues/7. I believe you will be able to reproduce the result following these links.
